Fix Deploy (master) workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,15 +14,16 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Set image name
+      - name: Validate secrets
         run: |
-          echo "IMAGE_NAME=${{ secrets.MODEL_NAME }}" >> $GITHUB_ENV
-          - name: Validate secrets
-            run: |
-              if [ -z "${{ secrets.DOCKER_USER }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
-                echo "Missing DOCKER_USER and/or DOCKER_PASSWORD secrets" >&2
-                exit 1
-              fi
+          if [ -z "${{ secrets.DOCKER_USER }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "Missing DOCKER_USER and/or DOCKER_PASSWORD secrets" >&2
+            exit 1
+          fi
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
       - name: Docker login
         uses: docker/login-action@v3
         with:
